### ISSUE TITLE
UserWarning: User configuration file unavailable

### ISSUE THREAD

**Issue by zhaoyongqi2022** [EFS-OpenSource/OSC-Generator#37]
Hi,

I installed the package and set up everything. Then I wanted to try the example.py. However, I got the following error feedback:

osc_generator\tools\user_config.py:46: UserWarning: User configuration file unavailable. warnings.warn("User configuration file unavailable. ", UserWarning)

How to fix it?

Btw, I didn't want to use "Open Simulation Interface (OSI) Format Input", so I didn't install OSI. Thus, for the tests, I got the following error feedback when running "test_converter.py" and "test_osc_generator.py":

warnings.warn("Feature OSI Input Data is not available. Download from: https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/format/OSITrace.py", UserWarning)

**Comment by zhaoyongqi2022** [comment]
Also, when runing the example.py the following error feedback comes:

![Error_Message](https://github.com/EFS-OpenSource/OSC-Generator/assets/99179657/1333d32c-0975-4441-9c9a-f61999e93763)

**Comment by DaveDsaEFS** [comment]
Hi Yongqi,

Thanks, the bug should be fixed and the updated state is in the develop branch, and should be merged into main shortly.

Regarding the warning messages; they are there to simply inform the user that the OSI interface may not be available (in case it is desired), and similarly that a user_config file is not provided (or cannot be found) in the case the user wants to set some object data (such as bounding box dimensions).

In both cases (if the user is not attempting to use an OSI interface or a config file), the generation of an xosc file, and the tests, should be successful.
