### ISSUE TITLE
Lower the version restrictions in requirements.txt

### ISSUE THREAD

**Issue by AxelAignerEFS** [EFS-OpenSource/OSC-Generator#6]
As a software developer
i want the dependency versions specified in requirements.txt to be less restrictive,
so that i can use osc-generator in combination with other packages depending on slightly different versions.

**Comment by DaveDsaEFS** [comment]
Removed version specifiers from  dependencies in requirements.txt.
Latest  package versions will be installed.
Tested for existing pytests -> tests pass
